version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - GCP_PROJECT_ID=${GCP_PROJECT_ID}
      - PORT=8080
    depends_on:
      - firestore-emulator
    
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8080
      - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
    depends_on:
      - backend
  
  firestore-emulator:
    image: gcr.io/google.com/cloudsdktool/google-cloud-cli:latest
    ports:
      - "8081:8081"
    command: gcloud beta emulators firestore start --host-port=0.0.0.0:8081
